export const TYPES = {
  EACH_ORDER: "EACH_ORDER",
  ALL_ORDERS: "ALL_ORDERS"
};

export const PRODUCT = {
  SET_PRODUCTS_BARCODE: 'SET_PRODUCTS_BARCODE',
  GET_TOP_PRODUCTS: 'GET_TOP_PRODUCTS',
  SET_PRODUCT_FOR_RECEIVE_ITEM: 'SET_PRODUCT_FOR_RECEIVE_ITEM',
  RESET_PRODUCT_FOR_RECEIVE_ITEM: 'RESET_PRODUCT_FOR_RECEIVE_ITEM',
  CLEAR_SEARCHED_PRODUCTS: 'CLEAR_SEARCHED_PRODUCTS',
  SEARCHED_PRODUCT: 'SEARCHED_PRODUCT',
  SEARCHED_PRODUCT_FAIL: 'SEARCHED_PRODUCT_FAIL',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_ID: 'UPDATE_PRODUCT_ID',
  UPDATE_PRODUCT_STATUS: 'UPDATE_PRODUCT_STATUS',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  GET_PRODUCT_FOR_EDIT: 'GET_PRODUCT_FOR_EDIT',
  UPDATE_DELETED_BY_CATEGORIES: 'UPDATE_DELETED_BY_CATEGORIES',
};


